### ISSUE TITLE
Installing the zip downloaded from github does not install the addon

### ISSUE THREAD

**Issue by kone9** [godotengine/godot-blender-exporter#1]
![2018-01-28 21_39_09-blender user preferences](https://user-images.githubusercontent.com/12847027/35489300-bf1cd7c2-0473-11e8-93b4-ca485f27942d.jpg)
![2018-01-28 21_38_47-blender_ c__users_ariel_desktop_tutoriales godot_archivos externo proyecto caba](https://user-images.githubusercontent.com/12847027/35489302-cb27e99e-0473-11e8-9935-79d3b47151f9.jpg)

**Comment by ni-code** [comment]
I can see the exporter option, but I'm on linux, maybe the bug affects only windows OS's. 
![godot_engine_expoter](https://user-images.githubusercontent.com/10292929/35490224-1a64d3a6-0496-11e8-90c6-12e8f192d1ae.png)

**Comment by ni-code** [comment]
Actually I see you don't have the correct add-on enabled. You have "Godot export manager" add-on enabled,  but you need to enable the "Godot engine exporter".

I think you just made a mistake and you enabled the wrong add-on.

![screenshot from 2018-01-29 01-47-33](https://user-images.githubusercontent.com/10292929/35490318-c7277666-0496-11e8-9fe6-0c24839aa7e7.png)

**Comment by kone9** [comment]
Hola,descargue el zip del repositorio,pero en windows solamente reconoce el godot export manager,no aparece el godot export engine manager
![2018-01-28 23_17_01-godot engine s native blender exporter add-on](https://user-images.githubusercontent.com/12847027/35490874-6704af8e-0481-11e8-96b2-7b25a3567660.jpg)

**Comment by kone9** [comment]
Hola,descargue el zip del repositorio,pero en windows solamente reconoce el godot export manager,no aparece el godot export engine manager
Hello, download the repository zip, but in windows only recognizes godot export manager, godot export engine manager does not appear
![2018-01-28 23_18_53-blender user preferences](https://user-images.githubusercontent.com/12847027/35490927-b9bd5d98-0481-11e8-8368-ebd12770c239.jpg)

**Comment by ni-code** [comment]
Then, it must be a bug.

Entonces, debe ser un error. (mi español es terrible, lo siento)

**Comment by kone9** [comment]
ok,thanks

**Comment by Calinou** [comment]
I'll close this issue, as it's very old and no longer applies to the latest version of Blender and the add-on.
