### ISSUE TITLE
First keyframe not positioned at the start of the animation time range

### ISSUE THREAD

**Issue by muiroc** [godotengine/godot-blender-exporter#110]
**Version**
exporter 9a9c851567d9d53e633fbaea9fa6605c68900674
godot 13eaded
blender 2.79b

Tried with single action export and with nla strips export (see escns in the sample)
Also tried the nla_with_active_action.blend in the tests folder

Also tried moving the actions keyframes at 0 and moving back 1 frame the NLA strips and their action extent's start frame (no idea what I was doing at that point :smiley:), or just moved the strips, but nothing changed

Comparison with the godot blender collada exporter
![compared](https://user-images.githubusercontent.com/10036337/48147386-784ced00-e2b7-11e8-8136-5af69c52a151.png)

Could be that I'm doing something wrong since to me the NLA editor is still confusing (action and actionclip start/end, strip position/start/end/ scale... etc)

**Sample Project**
[bug_blender_escn.zip](https://github.com/godotengine/godot-blender-exporter/files/2558401/bug_blender_escn.zip)

**Comment by Jason0214** [comment]
closed via #112
