### ISSUE TITLE
export concave / raw polygon physic collision shape export empty mesh

### ISSUE THREAD

**Issue by Olm-e** [godotengine/godot-blender-exporter#111]
when exporting a collision shape set in blender as mesh shape, the import in godot is correctly set to concave polygon but shows no shape

here is an example test file 

[testcube.blend.zip](https://github.com/godotengine/godot-blender-exporter/files/2561047/testcube.blend.zip)

**Comment by Jason0214** [comment]
seems the same as mentioned in this PR #85

**Comment by Jason0214** [comment]
Should be fixed by #245
