### ISSUE TITLE
Animation has a frame offset when constraints are enabled

### ISSUE THREAD

**Issue by muiroc** [godotengine/godot-blender-exporter#114]
**Version**
ba02eb0a17f38ecd2dcc9bae1bcccf0f94d2006d
blender 2.79b

Sorry for the long issue!

**Issue**
Please follow this sample project [bug_blender_escn_2.zip](https://github.com/godotengine/godot-blender-exporter/files/2574062/bug_blender_escn_2.zip)

Frame 0 of these "walk" animations:
![offset_at_frame_zero](https://user-images.githubusercontent.com/10036337/48378064-ee928a80-e6cf-11e8-956c-01d96e973285.png)

When exporting NLA strips and constraints are active, the resulting animation has that weird frame offsets, as if the source action was sampled some frames in advance, I'm pretty sure its a 2 frames difference,
Now why this offset of 2?

I'm going to report some more in depth findings but they are from another project/context: exporting an nla strip with range(1,32) stashed from an action with first/last keyframes(1,32)

I tried (and failed :smile:) debugging and solving it but maybe found something related in the ActionStrip wrapper:

when exporting with [no active action / with constraints / with export stashed]:
-action_strip { fk=0.96875, fb=2, frame_range=(1,33) }

when exporting [active action / no constraints / no stashed]
-action_strip { fk=1, fb=0, frame_range=(1,34 <-- this 34 is for a double end keyframe issue later... ) }

So fb==2 is the offset!

and indeed the first keyframe's computed location.y in
https://github.com/godotengine/godot-blender-exporter/blob/ba02eb0a17f38ecd2dcc9bae1bcccf0f94d2006d/io_scene_godot/converters/animation/action.py#L166
is 0.8163148760795593, (in blender the THIRD keyframe's location.y is 83.5146cm)

It could be that, when taking the baking branch here:
https://github.com/godotengine/godot-blender-exporter/blob/ba02eb0a17f38ecd2dcc9bae1bcccf0f94d2006d/io_scene_godot/converters/animation/animation_data.py#L104
the effects of get_action_frame_range() (that is, adding +1 to the range end) are accumulated later in the ActionWrapper's constructor:
https://github.com/godotengine/godot-blender-exporter/blob/ba02eb0a17f38ecd2dcc9bae1bcccf0f94d2006d/io_scene_godot/converters/animation/animation_data.py#L117

Tried just removing the +1 in get_stuff_frame_range and the animations starts ok but the linear remap is still needed so its not enough

**Related Issue**
Exporting only the active action (with constraints) adds 1 extra keyframe:

box_active_action_no_stashed_no_constraints.escn (duration: 1.03, keyframes: 31)
box_active_action_no_stashed_with_constraints.escn (duration: 1.07, keyframes: 32)

also, in both, there is a gap from the last keyframe position and the duration end

**Comment by Jason0214** [comment]
Well, the issue is exactly in the baking constraint range, I incorrectly add one frame, so that after a linear transform there would be an offset, and it also explains 
>Exporting only the active action (with constraints) adds 1 extra keyframe:

Really appreciate your detailed report and digging into my code (that part is not very readable), it saves me lot of time to find the bug. Thank you again!

----

>also, in both, there is a gap from the last keyframe position and the duration end
I think you are talking about the animation `length`? Yeah, seems it has one extra frame time there
![image](https://user-images.githubusercontent.com/19422835/48601875-36125400-e926-11e8-9fb3-d44ceadf5189.png)
I will solve it in another PR.
