### ISSUE TITLE
Impossible to export shapekeys animation with blender exporter

### ISSUE THREAD

**Issue by frankiezafe** [godotengine/godot-blender-exporter#115]
After a good session of trial and error, i had not been able to find a way to export shapekeys animation via the better collada exporter.

I did some research and built a "ducktape" solution via a python script for belnder and a manual copy/paste in .tscn files, described here: https://gitlab.com/snippets/1777687

Keep on the good work! Godot rocks!

**Comment by Jason0214** [comment]
Actually here is godot-blender-exporter not better-collada-exporter 😅, maybe you miss downloaded it?   and you are right better-collada doesn't have a support for shape key animation, but this exporter already has.  
I have looked your snippets, it is very similar with what this exporter implemented, thank you anyway.

Godot rocks, Cheers!
