### ISSUE TITLE
Normal map and tangent exporting checkup

### ISSUE THREAD

**Issue by Jason0214** [godotengine/godot-blender-exporter#118]
This is a checkup ensuring this exporter still export `tangent` and `normal map` after https://github.com/godotengine/godot/pull/23760 merged.

( I am a little lost in godot's tangent space, different handness stuff.. so I just build scene and visually checking the correctness,  both d3d normal map (i.e. negative green) and openGl normal map (i.e. positive green) are tested, I hope it is sufficient

**blender version**: *2.79a*
**godot version**: both *3.0.6* and *custom build 3.1* (build with [fix_tangent_direction branch](https://github.com/BastiaanOlij/godot/tree/fix_tangent_direction))
**platform**: macOS *10.13*
**godot-blender-exporter version**: current head [a7c022](https://github.com/godotengine/godot-blender-exporter/commit/a7c0022374b6a78fe05c905d0430b0a66d7cdc25)
**testing project**:  [tangent_checkup.zip](https://github.com/godotengine/godot-blender-exporter/files/2603284/mesh_tangent_checkup.zip)

----
### Tangent
I created simple meshes (cube, plane and sphere), uv unwrap them, and then export to escn file. **Normal map textures are applied inside godot**, so it is checking for correctness of tangent value.

open escn in Godot 3.0:
<img width="1221" alt="screen shot 2018-11-20 at 20 27 43" src="https://user-images.githubusercontent.com/19422835/48826697-ed8cd900-ed1f-11e8-803c-187103085945.png">

open escn in Godot 3.1
<img width="1142" alt="screen shot 2018-11-20 at 20 42 26" src="https://user-images.githubusercontent.com/19422835/48826718-f9789b00-ed1f-11e8-9997-21869518ec86.png">

<del>Using both DX and GL example normal map texture seems rendering to correct result. </del>
*actually the shadow position is not right*

----
#### Cycle Material
Also I tested exporting normal map in cycle material. Here I create meshes (cube, plane and sphere), uv unwrap them, **assign a normal map only cycle material to mesh in blender**, then export to escn file.

The scene in blender looks like:
<img width="587" alt="screen shot 2018-11-20 at 21 50 58" src="https://user-images.githubusercontent.com/19422835/48827147-38f3b700-ed21-11e8-83b5-c8c92c34a59f.png">

open escn in Godot 3.0
<img width="692" alt="screen shot 2018-11-20 at 22 03 21" src="https://user-images.githubusercontent.com/19422835/48827172-53c62b80-ed21-11e8-80e8-5714eb850b40.png">

open escn in Godot 3.1
<img width="805" alt="screen shot 2018-11-20 at 22 26 48" src="https://user-images.githubusercontent.com/19422835/48827183-5aed3980-ed21-11e8-8ab1-29b32b51eee3.png">

<del>As the exporter should export the scene as it is in blender, I think it is also correct.</del>
*actually the shadow position is not right*

-----

**Bugs**:
1. Tangent not right, cross product of tangent and binormal should be inverted

2. exporting the normal map in cycle material to escn generated a very low resolution normal map when zoomed in, the issue is texture are not detected as `normal map` by godot, so missing some conversion steps
<img width="486" alt="screen shot 2018-11-20 at 23 40 28" src="https://user-images.githubusercontent.com/19422835/48827284-aef81e00-ed21-11e8-960f-a3b8ac7a746c.png">

**Comment by Jason0214** [comment]
CC @akien-mga @BastiaanOlij

**Comment by Calinou** [comment]
> It looks like a texture mipmap issue, or under/over sample ? (which somewhat make sense, as there is no way in escn to tell godot that particular texture is a normal map texture in importing it )

Try selecting the texture(s) in the **Import** dock then set the compression mode to **Lossless** instead of **Video RAM**.

(I think Godot should be doing this by default for low-resolution textures where VRAM compression is not worth it, even if they're used in 3D.)

**Comment by Jason0214** [comment]
@Calinou after some experiment, I found it is the `Normal Map` option that really caused that buggy behaviour
<img width="200" alt="screen shot 2018-11-21 at 21 28 30" src="https://user-images.githubusercontent.com/19422835/48883390-7f561e00-edd4-11e8-9126-49930bef14e8.png"> 
apparently the shader script generated by this exporter is pool, so godot not able to detect texture as normal map.

**Comment by Jason0214** [comment]
@BastiaanOlij, Ah, finally I noticed the shadow beside the bump is not correct. Will make a PR soon to invert the tangent,bitangent cross product

**Comment by BastiaanOlij** [comment]
@Jason0214 Cool! I don't think I'll get to it tonight but I'm sure going to be playing with this over the weekend, then I can give some proper further feedback.

**Comment by Jason0214** [comment]
Really appreciate it! it would definitely if you can have a check on it.
