### ISSUE TITLE
Support for Blender 2.8?

### ISSUE THREAD

**Issue by kone9** [godotengine/godot-blender-exporter#122]
working en Blender 2.8???
Funciona en Blender 2.8???

**Comment by akien-mga** [comment]
Try it..?

**Comment by Jason0214** [comment]
The last time I check on blender2.8 ( months ago ), it still missing several python interfaces,  so I did not move on with it.  I will take a look at it these days.

**Comment by keletsorabalao** [comment]
I've just tried installing it. It doesn't show up in the Addons

**Comment by Jason0214** [comment]
@keletsorabalao The addon register API in blender28 has been changed (and a lot more API breaking change), so the current master would not work on it.

**Comment by Jason0214** [comment]
Primitive support for blender2.8 on [branch blender2.8](https://github.com/godotengine/godot-blender-exporter/tree/blender2.8), I will close this thread for now. 

If you test 2.8 branch and find some buggy behavior later, better to create other issues dedicate to specific bug.

**Comment by kone9** [comment]
Gracias descargado y ahora lo comparto en la comunidad
