### ISSUE TITLE
Armature animations need manual pre-bake (in Blender)

### ISSUE THREAD

**Issue by AntohaRDNS** [godotengine/godot-blender-exporter#139]
**OS:**
macOS 10.13

**Godot version:**
Godot Engine 3.1 beta.calinou.9ed34d4

**Blender version:**
Blender 2.79 cac3e16cfb76

**Issue description:**
Armature animation not working
without manual baking in Blender

**Comment by Jason0214** [comment]
Are you using any modifiers or constraints in your armature?   currently exporter only automatically detect IK constraint and baking it, there might be other constraints it not handled. If that is the case, could you please give a little more information about what is your armature and animation like?

**Comment by AntohaRDNS** [comment]
I use a simple armature with a single bone chain (4 bones). Without any constraints.
Tested with a simple bend animation.

**Comment by Jason0214** [comment]
Sorry I am able to tell where could be wrong based on your description, could you upload a minimal blend scene which can produce your issue?  that would be really helpful.

**Comment by Antokolos** [comment]
@Jason0214 , please take a look at the https://github.com/godotengine/godot-blender-exporter/issues/148 , I tried to create reproduction projects, that seems to relate to this issue
