### ISSUE TITLE
rename pep8 to pycodestyle

### ISSUE THREAD

**Issue by Jason0214** [godotengine/godot-blender-exporter#14]
we are using ```pep8``` for static analysis and it is now being renamed to [pycodestyle](https://github.com/PyCQA/pycodestyle/issues/466).However we need to make sure the new pycodestyle package can be found across all the popular platform (we may have developers work in different environment) before we simply rename it.

**Comment by sdfgeoff** [comment]
Good idea - in a week or two when Ubuntu 18.04 is released. If I recall correctly, the current LTS versions of Ubuntu have packages for pep8 instead of pycodestyle.

**Comment by sdfgeoff** [comment]
Note to self for later: the travis build agent runs Ubuntu 14.04 (gasp). We'll have to find a way to get pycodestyle onto the travis agent (or update the travis agent) when we make this change.

**Comment by akien-mga** [comment]
Well you can just change the Makefile to look for the available of `pycodestyle`, and if missing fallback to `pep8` (and if missing throw an error).

@Jason0214 Please be more specific in your issue descriptions, I literally had to grep the source code for `pep8` to see *where* `pep8` was used and then infer by myself why it would need to be renamed at all.

**Comment by Jason0214** [comment]
edited the description, thank you @akien-mga for your very kind suggestion, I will pay more attention next time

**Comment by Jason0214** [comment]
I can get ```pycodestyle``` on ubuntu 16.04 through ```pip3 install ```. But I am not sure if ```pip3``` on ubuntu 14.04 has it (hopefully it will have), I can build a VM and test it this weekend. 
If ```pycodestyle``` can not be found on travis,  how about we rename ```pep8``` to ```pycodestyle``` in Makefile, while still keep using ```pep8``` on travis and pass argument ```PYCODESTYLE=pep8``` to Make in travis.yml. Considering the python version we are using( < 3.5), I suppose the old ```pep8``` has the same behavior as ```pycodestyle```.   @sdfgeoff

**Comment by sdfgeoff** [comment]
Resolved in #17
