### ISSUE TITLE
Armature animations need manual pre-bake (in Blender), with examples

### ISSUE THREAD

**Issue by Antokolos** [godotengine/godot-blender-exporter#148]
**OS:**

Windows 10, 64-bit

**Godot version:**

3.0.6

**Blender version:**

2.79

**Issue description:**

This issue is probably related to https://github.com/godotengine/godot-blender-exporter/issues/139 , but I decided to make another issue for that.
Please take a look at the Vasya_test7.blend. It is a human model with some animations.
Now export it to Godot with the following parameters:
![image](https://user-images.githubusercontent.com/7196697/51827710-365ea080-2314-11e9-8117-2c7d9c737e21.png)
Immediately after export notice, that model is changed in Blender (arm bone was deformed, hopefully it seems not affecting the blend file itself):
![image](https://user-images.githubusercontent.com/7196697/51827807-67d76c00-2314-11e9-9ee9-0cd364058360.png)
Open exported file in the Godot, open the animation named "vasya_sidewalk_with_rifle_hands", note that it is clearly not was expected:
![image](https://user-images.githubusercontent.com/7196697/51827971-c43a8b80-2314-11e9-9e6f-1ec874581814.png)
Now, go into Blender again, remove all animations from the NLA editor and bake all of them manually with the following parameters (please note that the end frame is different for different animations):
![image](https://user-images.githubusercontent.com/7196697/51828058-f1873980-2314-11e9-9d50-00bdd0a24767.png)
The resulting file is Vasya_test7_bake.blend
Export this file to the Godot with the same parameters. Now you can see, that animation works as intended:
![image](https://user-images.githubusercontent.com/7196697/51828126-21ced800-2315-11e9-9fa1-2640a438ed59.png)

**Minimal reproduction project:**

[Vasya_test7_bake.zip](https://github.com/godotengine/godot-blender-exporter/files/2802308/Vasya_test7_bake.zip)
[Vasya_test7.zip](https://github.com/godotengine/godot-blender-exporter/files/2802309/Vasya_test7.zip)

**Comment by Jason0214** [comment]
fixed by #151,  really appreciate you give the example rig,  it helps me a lot to identify the issue.

**Comment by Antokolos** [comment]
Great news, thank you for your work!
