### ISSUE TITLE
Support export CYCLE/EEVEE material as Visual Shader material

### ISSUE THREAD

**Issue by Jason0214** [godotengine/godot-blender-exporter#158]
Currently there is a primitive implementation of export CYCLE/EEVEE material to Godot Shader material, it is useful as it could cover more general shader node trees.  However, it has some cons which is it is not convenient and straightforward for artist to adjust(before Shader Material support fully complete, adjust is required 😅)  

Several users have mentioned the desire of exporting to Spatial Material,  it could be done for simple shader node tree, for example a `principle BSDF node` with only value socket and texture input. It could be nice to have and not hard to implement

**Comment by Jason0214** [comment]
After some thinking, maybe it would be a better idea to focus on Visual Shader. It can be flexible in shader as well as user friendly to edit

**Comment by rezgi** [comment]
Hi everyone, I've been wondering how much of Blender's shaders made in its graph editor can be imported to Godot 3.2. In the docs, it says the following isn't supported : 

> all the noisy textures
> generated texture coordinates
> group node
> shader nodes except PrincipledBSDF, Diffuse, Glossy, Glass, add shader and mix shader

What's the actual state of the exporter ? Thanks.

**Comment by Jason0214** [comment]
Hi, thanks for your interests in your addon.
The part you referred in the doc is about the script shader, not visual
shader. (Also part of the doc is outdated )
For visual shader, I had plan to support and did part of development, but
it is still not usable right now. It is going slow because lack of energy
and I can not really tell when it will complete.

**Comment by rezgi** [comment]
Hey there. Thanks for your reply. Sorry I wasn't clear, I was mentioning the visual shader editor of blender, and convert this to a shader in Godot, visual or not. 

The most important part is how much of the Blender shader works the same in Godot as in Blender, and I'd like to know what are the features available in the present day. 

Thank you very much.

**Comment by Jason0214** [comment]
The doc is basically right. Currently it *does not support *
   1. all the Noisy texture nodes
   2. Group node
   3. Shader node except PrincipledBSDF, Diffuse, Glossy, Glass, AddShader
and MixShader
   4. Part of the Math nodes and Converter nodes which are not commonly used

Also some of the shader nodes like Glossy, Glass and MixShader may not be
artistically correct right now.

**Comment by rezgi** [comment]
Yeah thought so. So I need to find a way to adapt the assets made in Blender. Thank you very much for your answers. Hope this repo gets better with time !

**Comment by kalbfled** [comment]
Nearly 2 years later, is there any specific plan to support noise nodes?

I read in the docs and another issue that this is difficult to implement, but its absence precludes me from using this exporter for much of my work.  I know I could bake images, or maybe Material Maker would work.  (I think Material Maker has a Perlin node.)  Either way, that's another step in my workflow.  I would love to be able to export to ESCN and be finished.

**Comment by Calinou** [comment]
> I know I could bake images, or maybe Material Maker would work. (I think Material Maker has a Perlin node.) 

Material Maker has a lot of noise nodes available, surely Perlin or an equivalent is available there.

**Comment by Jason0214** [comment]
Hi @kalbfled, some personal change made me not having the time/resource to carry on the plan I made a while ago. As you can see there are not much progress on the exporter since then. Really sorry about it.

**Comment by kalbfled** [comment]
No worries, @Jason0214.  Thank you for the work you've already completed.
