### ISSUE TITLE
Principled BSDF transmission not exported

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot-blender-exporter#159]
**OS:**

Linux

**Godot version:**

3.0.6

**Blender version:**

Blender 2.79 (sub 6)
	build hash: 2c0c1f494dcf

**Issue description:**

1. Add a principled shader to a mesh
2. Increase transmission above 0
3. Observe that light passes through the mesh in blender
4. Export to Godot
5. Observe that light does _not_ pass through the mesh in godot

**Minimal reproduction project:**

[example.zip](https://github.com/godotengine/godot-blender-exporter/files/2849468/example.zip)
![1549837007](https://user-images.githubusercontent.com/2496231/52540509-1d181400-2d58-11e9-9ac6-93ac1c18259c.png)
![1549837017](https://user-images.githubusercontent.com/2496231/52540510-1d181400-2d58-11e9-9496-cb26c078c6c0.png)

**Comment by Jason0214** [comment]
Yes, I deliberately removed the exporting of transmission when I first implement it. At that time, transmission for thick object just not working, as the exporter has no context of the shape of object, I made it not exporting transmission.  

However, I just did a simple test on latest godot, seems transmission works for arbitrary shape object, maybe it's time to support it.
