### ISSUE TITLE
Limit precision of exports

### ISSUE THREAD

**Issue by sdfgeoff** [godotengine/godot-blender-exporter#16]
Currently the exporter produces things like:  
`Vector3Array(-6.572353328238023e-08, 0.0, -1.0, -1.0, -0.4999999701976776, ...`  

Which can obviously be better represented as:  
`Vector3Array(0.0, 0.0, -1.0, -1.0, -0.5, ...`

Fixing this will decrease filesize and may also solve some cross-platform differences in the reference-exports.

**Comment by sdfgeoff** [comment]
Note to implementer: If you change the functions in `encoders.py` to use the `Array` object in  `structures.py` then you'll only have to implement this in a single place (probably).

It may be good to merge encoders and structures, as they do pretty similar things.

**Comment by sdfgeoff** [comment]
Working on in https://github.com/simedis/godot-blender-exporter/tree/precision but the architecture makes it hard to pass a value from the UI down to the serialization. It seems that blender is only precise to about 6DP (default cube has vertices at 0.999999), so that's what I've currently got it set to.

I'll have a think if there is a more intelligent way to do the rounding, otherwise @akien-mga, do you think that a fixed value of 6DP is adequate

**Comment by akien-mga** [comment]
6DP sounds fine to me, yes. If some users need more precision, they'll request it (but I'm not sure we can be much more precise than that in Godot anyway until we finish double-precision floats support).
