### ISSUE TITLE
Exported materials not assigned to object slots

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot-blender-exporter#160]
**OS:**

Linux

**Godot version:**

3.0.6

**Blender version:**

Blender 2.79 (sub 6)
build hash: 2c0c1f494dcf

**Issue description:**

1. Export with "Generate External Materials"
2. Observe mesh in Godot
3. Material slots are `<null>` (I expected them to point at the exported `.material` files)

**Minimal reproduction project:**

Same as #159:
https://github.com/godotengine/godot-blender-exporter/files/2849468/example.zip

**Comment by Jason0214** [comment]
The issue is actually caused by the escn importing of Godot, when overwriting a same name `.material` file, the material resource may missing or be changed.   A simple example, if you have an `scene.escn`, it contains mesh 'A' with external material resource `mat.material`. When import `scene.escn` , if there is already `mat.material` is in that directory (which could caused by your last importing), these kind of issues could happen.

I have talked with reduz about this issue, he says this material reference system would be redesigned in the next version of Godot. Still, it may be worthwhile to open same the issue on Godot side and hoping for a temporary solution

**Comment by rcorre** [comment]
Thanks, I'll open an issue on the `godot` tracker.

However, it is worth noting that this happens even when exporting to a new project for the first time, when there isn't any existing material to overwrite. Does that still sound like the same issue?

**Comment by rcorre** [comment]
When I drag the exported material into the `null` slot, I see this diff in the scene:

```diff
diff --git a/untitled.tscn b/untitled.tscn
index 93b0c1e..c5c7b40 100644
--- a/untitled.tscn
+++ b/untitled.tscn
@@ -1,4 +1,6 @@
-[gd_scene load_steps=4 format=2]
+[gd_scene load_steps=5 format=2]
+
+[ext_resource path="res://Material.material" type="Material" id=1]

 [sub_resource type="Shader" id=1]

@@ -80,6 +82,7 @@ lod_max_distance = 0.0
 lod_max_hysteresis = 0.0
 mesh = SubResource( 3 )
 skeleton = NodePath("..")
-material/0 = null
+material/0 = ExtResource( 1 )
```

Would automatically adding an `ext_resource` to the `.escn` on export be enough to link it to the exported material?

**Comment by rcorre** [comment]
Here's what it looks like if I create a cube and assign an external material entirely in godot:

```
[gd_scene load_steps=3 format=2]

[ext_resource path="res://Material.material" type="Material" id=1]

[sub_resource type="CubeMesh" id=1]

custom_aabb = AABB( 0, 0, 0, 0, 0, 0 )
size = Vector3( 2, 2, 2 )
subdivide_width = 0
subdivide_height = 0
subdivide_depth = 0

[node name="Scene" type="Spatial" index="0"]

[node name="MeshInstance" type="MeshInstance" parent="." index="0"]

layers = 1
material_override = null
cast_shadow = 1
extra_cull_margin = 0.0
use_in_baked_light = false
lod_min_distance = 0.0
lod_min_hysteresis = 0.0
lod_max_distance = 0.0
lod_max_hysteresis = 0.0
mesh = SubResource( 1 )
skeleton = NodePath("..")
material/0 = ExtResource( 1 )
_sections_unfolded = [ "material" ]
```

So maybe if "External Materials" is set we could omit the embedded material entirely from the `.escn` and just add and `ext_resource` reference?

**Comment by Jason0214** [comment]
> However, it is worth noting that this happens even when exporting to a new project for the first time, when there isn't any existing material to overwrite. Does that still sound like the same issue?

well, then it seems not the same one as I described. 

> When I drag the exported material into the `null` slot, I see this diff in the scene:

Just to confirm that do you see `null` material at mesh object or at the mesh surface? This diff looks like you are assign material to the object. The exporter default export material to mesh surface (unless your material is `object` link in blender), so you would see two `null` material slots under the `Cylinder` object in your example.

> Would automatically adding an `ext_resource` to the `.escn` on export be enough to link it to the exported material?

Yes, that would definitely work. However, in my opinion generating 'real external material' on the exporter would put extra complexity on the exporter side, it would be the exporter's job to check the files in destination directory, avoid overwriting existed materials.  I still prefer it to be properly handled at godot side (which is also the current implementation), godot generating external material for `SubResource` with some special flags.

**Comment by rcorre** [comment]
Aha! It turns out I wasn't understanding the godot UI.
If I go to MeshInstance > Mesh >  Surface 1 I see the linked material.
I didn't get the distinction between object and surface materials.
Thanks!
