### ISSUE TITLE
Unable to find Godot project file

### ISSUE THREAD

**Issue by daniloulf** [godotengine/godot-blender-exporter#168]
**OS:**
Windows 10

**Godot version:**
3.1 beta

**Blender version:**
2.8 beta

**Issue description:**
When I try to export my rigged model into an escn-file I recive an error (look subject).

**Comment by lee12321** [comment]
Did you export the file to the godot project folder?

**Comment by sdfgeoff** [comment]
You can disable the material search (by default it searches for matching godot/blender material names)

**Comment by sdfgeoff** [comment]
By default Godot will search for the godot project in order to match materials (blender material name -> godot .tres file). This can be disabled with one of the export settings.

**Comment by daniloulf** [comment]
> Did you export the file to the godot project folder?

No I did not

**Comment by Calinou** [comment]
Judging by @sdfgeoff's comment, it seems this is done by design. You need to disable the aforementioned export setting if you want to export the `.escn` file outside a project.
