### ISSUE TITLE
Rigged mesh with Subsurf modifier and blend shapes creates deformed output

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot-blender-exporter#173]
**OS:**
Manjaro Linux 18.0.3

**Godot version:**
`master` / 8b231b96

**Blender version:**
Blender : 2.8 beta / 84820e
Exporter : `blender2.8` / a14b44d

**Issue description:**
When I export a rigged mesh with a Subsurf modifier and blend shapes, it creates a deformed output as shown in the below screenshot:
![화면 저장_20190309_112623](https://user-images.githubusercontent.com/2367032/54066163-08537100-426f-11e9-9d59-c87f1cc8aa31.png)

And as it's not allowed to actually apply a generative modifier to a mesh with blendshapes (this however had worked before, with the modifier being ignored with a warning), I tried to apply it using a script. But even when it successfully subdivided the mesh and removed the modifier, the exported output still got deformed in the same way as before.

**Comment by Jason0214** [comment]
yeah, it is weird that after apply the subdivision modifier the blendshape still not working, it should.  I understand subdivision is very important in modeling, this issue needs to be solved. Thank you for bring it up

**Comment by Jason0214** [comment]
I tested shape key with subdivision modifier on `blender2.8` branch, it works fine now. Maybe you can give a try?

Feel free to reopen :)
