### ISSUE TITLE
Cycles textures not showing up in Godot

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot-blender-exporter#175]
**OS:**

Linux

**Godot version:**

`3.1-beta9`

**Blender version:**

Blender 2.79 (sub 6)

**Issue description:**

1. Create a cube in blender
2. UV unwrap the cube
3. Assign a new principled BSDF material to the cube 
4. Assign [concrete_floor_02_Disp_1k.jpg](https://texturehaven.com/files/textures/jpg/1k/concrete_floor_02/concrete_floor_02_Disp_1k.jpg) to the base color
5. Scale the UVs in the UV editor (not sure why this is necessary, but the texture only appears in Blender after scaling the UVs, even if I barely change the scale).
6. Export to godot with the default settings
7. Open in godot
8. The texture is not shown

Based on issues like #72, it sounds like cycles textures should  be supported, so maybe I'm just missing a step somewhere, but I haven't been able to figure it out.

**Minimal reproduction project:**

[example.zip](https://github.com/godotengine/godot-blender-exporter/files/2949015/example.zip)

**Comment by corbac** [comment]
I'm In the same situation here.

OS:
MacOS

Godot version : 
3.1-beta11.oficial

Blender version:
2.8 beta 

Exporter : 
Branch 2.8 - a14b44

Issue description :
I exported my scene with 1 texture (cycles) I can't find it on Godot as well

**Comment by Jason0214** [comment]
@rcorre 

it is because no texture coordinate is specified in the material.  You can fix it by adding a texture input node and connect UV to the image texture's coordinate.

Here is an example if I change it to UV
![image](https://user-images.githubusercontent.com/19422835/54260967-b0935f00-4527-11e9-8dee-01e321936585.png)

**Comment by Jason0214** [comment]
@corbac 

could you try the latest blender2.8 commits at your convenience?   I think if there is any bugs, it is fixed now

**Comment by rcorre** [comment]
@Jason0214 that's it, thanks! For anyone reading, that means setting the `vector` input of the `ImageTexture` node to a `UV TextureCoordinate`.

![1552482345](https://user-images.githubusercontent.com/2496231/54281110-6504a380-456f-11e9-905e-b40d582966aa.png)
![1552482438](https://user-images.githubusercontent.com/2496231/54281126-6e8e0b80-456f-11e9-99be-bc05d344c8a1.png)

This is clear to close from my side.

**Comment by corbac** [comment]
I just tried different models with UV Mapping on PNG and JPEG textures. it works fine on Blender 2.8 Thanks \o/
