### ISSUE TITLE
Does the blender exporter support multiple nodes?

### ISSUE THREAD

**Issue by Raj2032** [godotengine/godot-blender-exporter#179]
![image](https://user-images.githubusercontent.com/29293830/54320847-87b3bc80-4642-11e9-9004-cc6b5b784443.png)

Take this image as an example, can we have mutiple nodes connecting each other and would the Godot exporter support this?

**Comment by rcorre** [comment]
Generally speaking, yes, the node tree will be exported as a `ShaderMaterial`. I know at least I've mixed a `Diffuse BSDF` and `Transparent BSDF`. If there's something specific that isn't working, could you describe it in more detail and include and example .blend file?

**Comment by Raj2032** [comment]
What about `Light Path` would that also work as you can see in this image. I have `Light Path` connected to `Mix Shader Frac` and I connected the other two emissions to the `Mix Shader` and then I output the result into the `Material Output`. Is this supported by the exporter? Would the exporter export this sort of stuff?

At the moment emissions is not supported by the exporter and I hope it can be exported in the future. Cause when I do export emissions property to Godot, the objects do not light up at all.

**Comment by rcorre** [comment]
> Is this supported by the exporter

Can you try it and let us know :laughing:? If it doesn't work, please attach a .blend file so we can investigate, as the issue template mentions.

> At the moment emissions is not supported by the exporter

Can you be more specific, and maybe include a .blend file for this as well? I see you brought this up on #153, but I'm not clear on the specific issue. Here's a scene with one emission and one diffuse object in a dark environment (godot above, blender below):

![1552565605](https://user-images.githubusercontent.com/2496231/54356095-220b0480-4631-11e9-85fe-e06367a10503.png)

The only difference is that the blender object actually casts light on other objects whereas the godot one doesn't, but I believe that is a limitation of Godot itself.

**Comment by Raj2032** [comment]
[Cube example.zip](https://github.com/godotengine/godot-blender-exporter/files/2966281/Cube.example.zip)

So try and export this to Godot and it will not support the emissions property at all using the Godot exporter.

**Comment by rcorre** [comment]
![1552567989](https://user-images.githubusercontent.com/2496231/54358372-9e541680-4636-11e9-9f63-82d2a7359fa4.png)

The emission export seems to work for me. Are you on the latest exporter version? What does it look like for you, and what are you expecting?

**Comment by Raj2032** [comment]
When was it last updated, cause I think I got the exporter a month ago.

Is the cube's emission reflecting to other objects?

**Comment by rcorre** [comment]
> When was it last updated, cause I think I got the exporter a month ago.

You can check https://github.com/godotengine/godot-blender-exporter/commits/master for updates, they happen pretty regularly right now.

> Is the cube's emission reflecting to other objects in Godot?

See [my comment above](https://github.com/godotengine/godot-blender-exporter/issues/179#issuecomment-472827763):

> The only difference is that the blender object actually casts light on other objects whereas the godot one doesn't, but I believe that is a limitation of Godot itself.

Try adding an emission material natively in Godot, you will see that it also does not cast light onto other objects.

You can pre-bake lighting with a [GI Probe](https://docs.godotengine.org/en/latest/tutorials/3d/gi_probes.html). If you want dynamic lighting, I believe you must use a lamp.

**Comment by Raj2032** [comment]
OK say that I have an object which has many materials to it, some parts has emissions to it. How would I attach a lamp right up a

**Comment by Raj2032** [comment]
@rcorre 

> You can pre-bake lighting with a GI Probe. If you want dynamic lighting, I believe you must use a lamp.

So lets just say i have an object made up of many objects (that are joined together) that has many materials, one includes emissions property. If I want to add a dynamic lighting, how would I perfectly line up the lamp to those specific sub emission objects right in the center of it?

**Comment by rcorre** [comment]
> Would Godot support emissions property natively in the near future?

You can ask at https://github.com/godotengine/godot/issues. I'm not an expert but I suspect it would be a significant amount of work.

> if I want to add a dynamic lighting, how would I perfectly line up the lamp

This question isn't clear to me, you can line up a lamp in blender however you like and export it to Godot. Can you give a specific example of what you're trying to achieve and what issues you encountered?

**Comment by Raj2032** [comment]
> This question isn't clear to me, you can line up a lamp in blender however you like and export it to Godot. Can you give a specific example of what you're trying to achieve and what issues you encountered?

Ok so say that I have a character that has 2 ico spheres as their eyes. How would I line up the lamps to make them glow, But as you mentioned that I can actually export the lamps from Blender to Godot this is good enough for me. Thanks.

**Comment by Raj2032** [comment]
@rcorre One question, what type of lamp would I use in Blender to substitute an emissions property?

**Comment by rcorre** [comment]
@Raj2032 only `point`, `spot`, and `sun` are supported by the exporter. I messed around a bit and got a "glowing eyes" effect using a mixed Emission/Transparent shader with Point lamps inside the eyes.

![1552612418](https://user-images.githubusercontent.com/2496231/54401499-4e109f00-469e-11e9-920a-0fc070dc0dce.png)
[example.zip](https://github.com/godotengine/godot-blender-exporter/files/2969047/example.zip)

**Comment by Raj2032** [comment]
@rcorre  For some reason when I tried to run it on Godot (the project that you sent me) I got this error.

```
ERROR: _load_settings_text_or_binary: Couldn't load file 'C:/Users/Raj/Deskt
op/example/example/project.godot', error code 12.
   At: core/project_settings.cpp:519
Mono: Runtime cleanup...
OpenGL ES 3.0 Renderer: GeForce GTX 260/PCIe/SSE2
Mono: Initializing module...
Mono: Runtime initialized
Mono: INITIALIZED
```

**Comment by Raj2032** [comment]
@rcorre 

![image](https://user-images.githubusercontent.com/29293830/54404986-40ecc200-4729-11e9-8ad1-5adec0b57a74.png)


Ok so the only problem I have over here is that how do I get my models to look fully solid, as I don't want it to look transparent?

**Comment by rcorre** [comment]
Not sure why the project wouldn't load, unless it is a version incompatibility (I created it with 3.1-beta9).

> how do I get my models to look fully solid

Two ideas:

1. Use two different materials. Make the front transparent but the back opaque
2. Use a Principled BSDF and play with the "Transmission" setting

![1552646147](https://user-images.githubusercontent.com/2496231/54425851-be461180-46ec-11e9-9821-c1249a0eba5e.png)

**Comment by Raj2032** [comment]
@rcorre 
> Not sure why the project wouldn't load, unless it is a version incompatibility (I created it with 3.1-beta9).

Yeah I am not using the Beta version I am using older version.


> 1. Use two different materials. Make the front transparent but the back opaque

![image](https://user-images.githubusercontent.com/29293830/54427173-d447e680-476d-11e9-88d2-3d8edfed3ff3.png)

Thats what I am doing, but when exported to Godot it becomes transparent. Am I supposed to be doing something differently? I mixed an emissions material with transparent. Did I set it up incorrectly or something?


> 2. Use a Principled BSDF and play with the "Transmission" setting

![image](https://user-images.githubusercontent.com/29293830/54427295-3bfe3180-476e-11e9-91ae-9f49e63f8609.png)

Doesn't look quite right, it looks like a lightbulb inside a glass cube. That style is not what I am going for.

**Comment by rcorre** [comment]
> I mixed an emissions material with transparent. Did I set it up incorrectly or something?

I'm suggesting two completely different materials on the same object:

1. A mixed emission/ transparent on the front side
2. A diffuse on the back side

> Doesn't look quite right, it looks like a lightbulb inside a glass cube

It looks like that in blender, but I found that in godot you don't get that single glowing point in the center. Also try tweaking the "Transmission Roughness".

Beyond that, I'm not sure exactly what you are looking for, and I've about hit the limits of my knowledge :)

**Comment by Raj2032** [comment]
Ok it actually now works I am using principled material thanks for your help :) But how does Principled work though?

**Comment by rcorre** [comment]
The [blender docs](https://docs.blender.org/manual/en/latest/render/cycles/nodes/types/shaders/principled.html) and [this blender guru video](https://www.youtube.com/watch?v=4H5W6C_Mbck) describe the principled BSDF pretty well.

**Comment by Raj2032** [comment]
Thanks
