### ISSUE TITLE
Feature Request: COA tools support?

### ISSUE THREAD

**Issue by rektuiemforameme** [godotengine/godot-blender-exporter#184]
This isn't an issue; sorry if this isn't the right place to put this.
    As you may know, COA tools [https://github.com/ndee85/coa_tools](url) is an addon for Blender that makes Blender possibly the best Cutout animation tool there is, due to Blender's extensive animation and mesh editing tools which go beyond what other tools like Spine and Dragonbones can do. COA tools currently has a json exporter and an importer for Godot, but they're kinda outdated and don't support 3.1's new cutout animation features like mesh deformation. 
    Are there any plans to support exporting COA tools created rigs/sprites/meshes/animations with this exporter? I wouldn't really expect there to be, but I thought I might as well ask.
Edit: I just tried exporting a COA tools project, and it did pretty much what you would expect. It kinda worked, but it exported as mesh instances and skeletons instead of polygon2Ds and skeleton2Ds. Also, the image texture didn't get exported so the images are just blue. I might look into this more myself

**Comment by sdfgeoff** [comment]
This tool is focused on the pipeline for 3D assets. While I like the idea of using blender for the 2D parts as well, it's probably better to create PR's against the Godot 2.1 CAO_Importer https://github.com/ndee85/coa_tools/tree/master/Godot/coa_importer
