### ISSUE TITLE
Can't export a model.

### ISSUE THREAD

**Issue by Raj2032** [godotengine/godot-blender-exporter#185]
So there is this particular model I want to export and I was attempting to export ONLY Mesh and Lamp.

![image](https://user-images.githubusercontent.com/29293830/54468863-2aa43c00-47e5-11e9-951d-8f3f45adc51e.png)

The model contains a child model parented to the main model, armature and 2 spot lights which are parented to the model. The model does also contain various materials as well.

Here is the error report that I get when I attempt to export the model.

![image](https://user-images.githubusercontent.com/29293830/54471046-aa8ece00-4806-11e9-9265-95a416bc7afa.png)

**Comment by Jason0214** [comment]
should be fixed in the current master HEAD.  Bad for me to write that bad code causing crash :(

**Comment by Raj2032** [comment]
@Jason0214 You're welcome mate :)

> Bad for me to write that bad code causing crash :(

Its all right I understand stuff like this happens all the time.
