### ISSUE TITLE
Does godot-blender-exporter support Glossy BSDF "Sharp"

### ISSUE THREAD

**Issue by Raj2032** [godotengine/godot-blender-exporter#187]
![image](https://user-images.githubusercontent.com/29293830/54475894-054a1900-484b-11e9-95d9-6514ff266c42.png)

As you can see in this image, if I export this model using Glossy BSDF "Sharp" does Godot support "Sharp" mode in Glossy BSDF and/or does the exporter export the Glossy BSDF "Sharp" as I couldn't really notice Godot rendering the "Sharp" mode of Glossy BSDF?

**Comment by Jason0214** [comment]
Well, I am not very familiar with rendering, but just give a try, what I am saying might be wrong.

First it is not supported by the exporter.
According to https://docs.blender.org/manual/en/latest/render/cycles/nodes/types/shaders/glossy.html, the `Sharp` is a distribution mode. As far as I know godot only supports GGX distribution.  And actually nowadays most of PBR game engines only supports GGX,  other distribution like such as `Multi-scattering GGX` are just too expensive(or has no good implementation) in realtime rendering.

**Comment by Raj2032** [comment]
@Jason0214 How do objects extra shiny then?

**Comment by Jason0214** [comment]
Maybe try to increase the `metallic` and reduce `roughness`?   (Empiric from my very little shader making experience).

**Comment by Raj2032** [comment]
@Jason0214 I will give that a shot then.
