### ISSUE TITLE
Armature with 2 bones only one shows in godot 

### ISSUE THREAD

**Issue by espofficial** [godotengine/godot-blender-exporter#195]
**OS:**
Windows

**Godot version:**
3.1

**Blender version:**
2.8

**Issue description:**
![image](https://user-images.githubusercontent.com/26037455/54882150-71360e00-4e57-11e9-8371-ad415b36a670.png)

Hello folks , I have this issue/bug , I don't know if it is the same for you so let me explain . 
I have a simple mesh with an armature , the armature has 2 bones , when I export the scene with the addon to godot (.escn) and I open the scene to inpect . Hiding the mesh and leaving only the skeleton only a bone appears !

![image](https://user-images.githubusercontent.com/26037455/54882180-ad696e80-4e57-11e9-8f87-c5bd7ed9d3d4.png)

Now in the inspector the bone exists but it doesn't show !
While giving to the mesh an extra bone , two of them show in godot while the last one doesn't show . Do you have such issue like me ? Any idea on how to make this thing work ? 

![image](https://user-images.githubusercontent.com/26037455/54882235-16e97d00-4e58-11e9-89ca-c2bfa19e96ed.png)

Thank you ,
Endrit .

ps. I'm using the 2.8 branch of the addon

**Comment by Jason0214** [comment]
might be the same issue as https://github.com/godotengine/godot/issues/18443

**Comment by espofficial** [comment]
> might be the same issue as [godotengine/godot#18443](https://github.com/godotengine/godot/issues/18443)

yeah it seems to be the same issue ! so the only way "to fix" it is to add an extra bone
