### ISSUE TITLE
Animations influence others later in the NLA stack

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot-blender-exporter#199]
**OS:**

linux

**Godot version:**

3.1-beta9

**Blender version:**

Blender 2.79 (sub 6)
	build hash: 2c0c1f494dcf

**Issue description:**

1. Set up several animations, each having keyframes for a different subset of bones
2. Push all animations onto the NLA stack
3. Notice that animations earlier in the stack influence animations later in the call stack

For example, here is my lean left animation:

![lean](https://user-images.githubusercontent.com/2496231/55288941-6a465880-538d-11e9-8e84-8afc17587d7f.png)

Here is my spin left animation:

![spin_left](https://user-images.githubusercontent.com/2496231/55288935-57338880-538d-11e9-8ea9-1ff654a79e84.gif)

Here's what it looks like in Godot:

![godot](https://user-images.githubusercontent.com/2496231/55288934-57338880-538d-11e9-99c3-0946c9f11626.gif)

**Minimal reproduction project:**

[example.zip](https://github.com/godotengine/godot-blender-exporter/files/3026559/example.zip)

**Comment by Jason0214** [comment]
after the fix, the 'turn' animation now looks like this:
![out](https://user-images.githubusercontent.com/19422835/55293027-3297da80-53a6-11e9-9707-2e526c1fd562.gif)

it is totally independent with others, but I suppose it may not be the one you want? (looks like you want it 'stands' and then 'turn'

**Comment by rcorre** [comment]
A little hard to tell with the speed of your gif, but I just tried this patch locally and the animation looks correct now. As an added bonus, exporting no longer modifies the current pose. Thanks for the quick fix!
