### ISSUE TITLE
Disconnected child bones merge at parent's head.

### ISSUE THREAD

**Issue by Skywolf285** [godotengine/godot-blender-exporter#205]
Windows/Godot 3.1/Blender 2.79

Bones which are parented but are not connected don't export properly. The head of these bones merge at the head of the parent. Changing the point of rotation which gives undesired deformation.

![inblender](https://user-images.githubusercontent.com/49045791/56099463-ad680600-5f0d-11e9-8fad-fa723fbc5446.png)
![Ingodot](https://user-images.githubusercontent.com/49045791/56099464-af31c980-5f0d-11e9-8d2e-4dc80956f651.png)

**Minimal reproduction project:**

[Godot Disconnected parented bone test.zip](https://github.com/godotengine/godot-blender-exporter/files/3077891/Godot.Disconnected.parented.bone.test.zip)

**Comment by Jason0214** [comment]
Actually Godot only support display bones connected. And this connectivity of bones is just a 'display', it does not affect functionality.  Skeleton bones is just `transform` + `vertex's weights`. So this is not an issue.

**Comment by Skywolf285** [comment]
Ah, I see. So if anything this is a Godot engine issue. Not one with the exporter.

Sorry for the inconvenience.
