### ISSUE TITLE
rotation_mode Quaternion (XYZW) animations produces error '!is_normalized() is true' in Godot

### ISSUE THREAD

**Issue by hedgehog90** [godotengine/godot-blender-exporter#216]
**Godot version:**
3.1.1.stable.mono.official

**Blender version:**
blender-2.80.0-git.fd3f75a02cf9-windows64

**Issue description:**
It seems any rotation keys on an object with rotation_mode Quaternion (XYZW) cannot be processed by Godot.
Produces the error:

> core/math/quat.cpp:150 - Condition ' !is_normalized() ' is true. returned: Quat()

The rotation of the object only updates on the keyframe according to the blender timeline, but not on any of the interpolated keyframes generated by the exporter.
Changing the rotation_mode to XYZ Euler fixes the issue.

**Minimal reproduction project:**
Godot project: [rotationbug.zip](https://github.com/godotengine/godot-blender-exporter/files/3216805/rotationbug.zip)
Blend file: [animation_parented_objects.zip](https://github.com/godotengine/godot-blender-exporter/files/3216839/animation_parented_objects.zip)

**Comment by Jason0214** [comment]
same as #142 

I tried force normalize on Blender side, but it can not solve this issue in all the platforms. Might be some precision issue either in Blender's normalize or Godot PoolVector reading. 

there is https://github.com/godotengine/godot/pull/28722 which solves this issue

**Comment by hedgehog90** [comment]
> same as #142
> 
> I tried force normalize on Blender side, but it can not solve this issue in all the platforms. Might be some precision issue either in Blender's normalize or Godot PoolVector reading.
> 
> there is [godotengine/godot#28722](https://github.com/godotengine/godot/pull/28722) which solves this issue

Before you linked to it I had already found it and using it. Thanks :)
