### ISSUE TITLE
2.80 branch: character mesh all over the place when playing the animation

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/godot-blender-exporter#226]
**OS:** Linux Pop_OS! 19.04

**Godot version:** 3.1.1 stable

**Blender version:** 2.80 beta (_commit 3128fe4_)

**Issue description:**

I tried to export our animated character Mannequiny with the 2.80 branch, using a recent build of blender 2.80. Using the default options, the character mesh looks fine in T-pose, the armature looks fine, but not the mesh:

![Screenshot from 2019-06-27 10-54-11](https://user-images.githubusercontent.com/12694995/60227336-ec311980-98c9-11e9-8de8-77b21e8b48cb.png)

You can find the blend test file and the exported escn file in the archive below. The unit system is set to metric and as some people recommended, I applied transforms on the armature and on the meshes.

I'm at your disposal if you need more information.

**Minimal reproduction project:**

[mannequiny-lite.zip](https://github.com/godotengine/godot-blender-exporter/files/3332565/mannequiny-lite.zip)

**Comment by Jason0214** [comment]
Most likely an issue in vertex weights (Bone weights).

**Comment by Jason0214** [comment]
Fixed by #227

**Comment by ThunderFD** [comment]
Holy shit! I think this fixed my riggify rig that I tried to get to work all day long!

**Comment by ThunderFD** [comment]
I do get a bunch of "vertex weights more than maximal" warnings, but I don't know if that's something to be concerned about. @Jason0214 if that's something that needs looking at, let me know, I could upload my blend file (2.80)

**Comment by Jason0214** [comment]
As long as your exported ESCN works as expected, then you don't need to worry about it.  It is related to the fact that Godot only supports *4* bones for every vertex, however, in blender you can have more than 4.   But usually the 5th (or more) bone would have a very small vertex weight, ignoring them does not affect visual results.

If you get this warning and also find your rigify looks slight different between godot and blender, you may need to adjust the skeleton to ensure that most vertices are significantly influenced only by 4 bones.

**Comment by ThunderFD** [comment]
I see, thanks a lot! 
as I haven't actually vertex painted yet (I wanted to test if it works with automatic weights first..) I have to adjust the weights anyway :)

**Comment by NathanLovato** [comment]
Thanks much for the fix :)
Now the animation mostly works. There are some jitters in Godot, but if it only supports 4 bones per vertex we should look into fixing that on the rig's side
