### ISSUE TITLE
Vertex weights more than maximal after limiting in blender

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot-blender-exporter#249]
**OS:**

Linux.

**Godot version:**

3.1.1.stable.custom_build

**Blender version:**

```
Blender 2.80 (sub 75)
	build date: 2019-07-30
	build time: 16:57:38
	build commit date: 2019-07-29
	build commit time: 14:47
	build hash: f6cb5f54494e
	build platform: Linux
	build type: Release
	build c flags:  -Wall -Wcast-align -Werror=implicit-function-declaration -Werror=return-type -Werror=vla -Wstrict-prototypes -Wmissing-prototypes -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wlogical-op -Wundef -Winit-self -Wnonnull -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Wformat-signedness -Wrestrict -Wuninitialized -Wredundant-decls -Wshadow -Wno-error=unused-but-set-variable -Wimplicit-fallthrough=5 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fuse-ld=gold -fopenmp -std=gnu11   -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -msse2
	build c++ flags:  -Wredundant-decls -Wall -Wno-invalid-offsetof -Wno-sign-compare -Wlogical-op -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Werror=return-type -Werror=implicit-function-declaration -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wundef -Wformat-signedness -Wrestrict -Wuninitialized -Wundef -Wmissing-declarations -Wimplicit-fallthrough=5 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fuse-ld=gold -fopenmp -std=c++11   -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -msse2
	build link flags:  -Wl,--version-script='/build/blender/src/blender-2.80/source/creator/blender.map'
	build system: CMake
```

**Issue description:**

I'm not sure if this is an issue with godot, blender, or me :grinning:

When I export from blender, I get the "Vertex weights more than maximal" warning even after running `Limit number of weights per vertex` with a value of 4 or 3.
If I run `Limit number of weights per vertex` with a value of 2, the warning goes away.

I realize that it probably won't make a practical difference, but

a) The flood of warnings is annoying
b) For a more complex rig, it _might_ mean that blender and godot won't match.

**Minimal reproduction project:**

[example.zip](https://github.com/godotengine/godot-blender-exporter/files/3490287/example.zip)

**Comment by Jason0214** [comment]
Could you explain more about the `Limit number of weights per vertex` part? is that some Blender option you can turn on to limit the vertex weight?


The issue here is that Godot only support at most 4 bone weight for each vertex, so when the blender mesh exceeds the 4 limit, warning msg is thrown.   I can see that warning message can get flooding when exporting  a complex rig, probably we can improve it to be more user friendly. But other than that, I don't think there is much we can do.

**Comment by rcorre** [comment]
`Weight Paint Mode > Weights > Limit Total` will limit the number of bones influencing to only the `N` largest weights. I found it on a [question asking about a similar limitation in Unity](https://www.reddit.com/r/Unity3D/comments/3zn24h/limits_of_bones/). However, it doesn't seem to be working for the godot exporter. I have to set it to 2 to make the warnings go away. I'm not sure if it is an issue with the exporter, blender, or just my understanding, but figured I'd report it here in case someone else experiences the same :grinning: 

![1565778669](https://user-images.githubusercontent.com/2496231/63015113-2183cd80-be5e-11e9-8244-a3efeae52fdb.png)

**Comment by rcorre** [comment]
Strange, I ran limit 4, and `[len(v.groups) for v in C.object.evaluated_get(bpy.context.view_layer.depsgraph).to_mesh(preserve_all_data_layers=True, depsgraph=bpy.context.view_layer.depsgraph).vertices]` still contains some 5's ... I don't think this is the exporter's fault.

![1565781887](https://user-images.githubusercontent.com/2496231/63017567-b4c00180-be64-11e9-87a7-bdba38ce7ad8.png)

**Comment by rcorre** [comment]
Filed https://developer.blender.org/T68668
