### ISSUE TITLE
Export scene with frame not set to zero

### ISSUE THREAD

**Issue by Jason0214** [godotengine/godot-blender-exporter#25]
the blender object's properties (e.g. transform) can be affected by animation. If a user build a scene which has an animation, but forget to set the frame to zero before exporting, it would generate a unwanted result. So maybe it should have a ```bpy.scene.frame_set(0)``` before the exporting procedure starts.

**Comment by sdfgeoff** [comment]
If you export it without enabling animations, then I'd expect it to export what the user sees in the viewport. So in my mind this is a non-issue.
