### ISSUE TITLE
Palette colors from magicavoxel no import in Godot

### ISSUE THREAD

**Issue by nuxlight** [godotengine/godot-blender-exporter#250]
Hi, 

I have a problem maybe it's due to my import from MagicaVoxel. After import the obj file in Blender i have all model colors. But after the export to Godot with godot-blender-exporter, i don't have the same colors applications on the model.
Is it due to my export options ?

Blender view :
![image](https://user-images.githubusercontent.com/2751135/62849394-ca57ee80-bcdf-11e9-9765-f1fa5c9f3fd8.png)

Export options :
![image](https://user-images.githubusercontent.com/2751135/62849497-228ef080-bce0-11e9-8c18-f62e3598b29e.png)

Godot view after import :
![image](https://user-images.githubusercontent.com/2751135/62849518-363a5700-bce0-11e9-8f20-15ee47678499.png)

Thanks for your help :)

**Comment by Jason0214** [comment]
Could you give me a description or screenshot of the material you are using?   it is too less information for me to find out the issue.

Also I am a little curious about the material ball in your first screenshot, the material in GodotEngine looks very similar to that material ball in blender, is it?

**Comment by nuxlight** [comment]
I have created a new thread on Godot Form and they have find a solution ;)
https://godotforums.org/discussion/comment/28845

**Comment by Jason0214** [comment]
Looks like the exported shader is using blender Generate Texture Coordinate as UV, while the expected behavior is to use UV from the mesh
