### ISSUE TITLE
optionally export gdscripts for each object

### ISSUE THREAD

**Issue by hartsantler** [godotengine/godot-blender-exporter#253]
while writting the escn file we could also write gdscripts that are linked to objects in blender. text nodes linked from `bpy.data.text` to an object via a simple custom property `gdscript`

**Comment by hartsantler** [comment]
The custom attribute `gdscript` now may also simply contain inline gdscript.
It is optional for it to be the name of a `bpy.data.texts` block, but this is still preferred.

Custom attribute `gdvs` works the same way, and will generate a godot VisualScript node linked the object.

**Comment by Jason0214** [comment]
That's a good idea and thanks for your work, I will have a look on your patch when have some time

**Comment by bojidar-bg** [comment]
Reopening as the related PR (#252) is not yet merged (and thus there is no support for this feature in the master branch yet).
