### ISSUE TITLE
export grease pencil objects

### ISSUE THREAD

**Issue by hartsantler** [godotengine/godot-blender-exporter#255]
is there a triangle strip mode in the escn format spec?

**Comment by hartsantler** [comment]
by setting the `primitive` draw mode to `5` we can support triangle strips for sub meshes.  Draw mode `3` is line-loop, and `2` is line-strip.

**Comment by hartsantler** [comment]
![Screenshot from 2019-08-17 19-45-00](https://user-images.githubusercontent.com/764882/63219527-43b07080-c128-11e9-89a3-cc5e47da2cbe.png)

**Comment by Jason0214** [comment]
Awesome！ thanks for your work.

**Comment by bojidar-bg** [comment]
Reopening as the related PR (#252) is not yet merged (and thus there is no support for this feature in the master branch yet).
