### ISSUE TITLE
option to export boolean modifiers as CSG

### ISSUE THREAD

**Issue by hartsantler** [godotengine/godot-blender-exporter#259]
we could have an option to support exporting objects with boolean modifiers as CSG objects, rather than converting it to a static mesh.
```
[node name="CSGSphere" type="CSGSphere" parent="."]
transform = Transform( 1, 0, 0, 0, 1, 0, 0, 0, 1, -1.30123, 0, 0 )
operation = 2
invert_faces = true
```

**Comment by Jason0214** [comment]
Pretty good, I like this idea

**Comment by bojidar-bg** [comment]
Reopening as the related PR (#252) is not yet merged (and thus there is no support for this feature in the master branch yet).
