### ISSUE TITLE
Principled shader texture export ignores UV layout

### ISSUE THREAD

**Issue by rokyfox** [godotengine/godot-blender-exporter#260]
**OS:**
LINUX

**Godot version:**
3.1.1

**Blender version:**
2.80

**Issue description:**
Exported a cycles material node setup that included an image texture, with the Vector input left unconnected. This defaults to generated texture coordinates (the 'AABB_UVW' variable in the code). The result is a wrong UV layout, since the UV map is ignored. If the 'UV' built-in variable is used instead, the coordinates are correct. This also requires changing the 'co' parameter for 'node_tex_image' from vec3 to vec2, or passing it as 'vec3(UV, 0.0)'.

**Minimal reproduction project:**
[project.zip](https://github.com/godotengine/godot-blender-exporter/files/3512117/project.zip)

In the above project, "House_Material.material" is the original exported material and "House_Material_fixed.material" is a slightly modified version which solves the problem in this case.

**Comment by Jason0214** [comment]
Well, I made it default to use the generated texture coordinate because I though it is what Blender does when the texture coordinate is not specified, is it?

**Comment by Jason0214** [comment]
Probably you are right, it should export UV when UV is present.  Similar issue reported in #250

**Comment by Jason0214** [comment]
Should be fixed by #263

**Comment by rokyfox** [comment]
Won't that cause issues in cases where there _isn't_ a UV map? I think blender does default to generated coordinates if no UV maps are available. Couldn't work out a way to check for maps in the code though.

**Comment by Jason0214** [comment]
I did check, in previous Blender version it do use Generated Texture Coord when there is no UVMap.  However, Blender2.80 does not.

It's not hard to passing a UVmap(either flag or entire object) done to Shader code, but I will do when it is really necessary.

Thank for pay attention to this detail!
