### ISSUE TITLE
Salvagable PR material out of range, boolean mod, new: gdscript, gdprim, gdcsg, grease pencil, reexport button

### ISSUE THREAD

**Issue by fire** [godotengine/godot-blender-exporter#265]
Material out of range, boolean mod, new: gdscript, gdprim, gdcsg, grease pencil, reexport button

Should be GPL licensed.

[252.txt](https://github.com/godotengine/godot-blender-exporter/files/3527062/252.txt)

**Comment by bojidar-bg** [comment]
The issues previously handled by that PR were closed by their author. Now, #266, #267, #268, and #269 take their place.

**Comment by hartsantler** [comment]
@fire you got alot of nerve taking my code and saying its GPL licensed.
I was in the beginning willing to contribute many improvements to this exporter under the GPL.
Not anymore thanks to back stabbers like you, and Elitist Google losers like, @Jason0214

**Comment by dodgyville** [comment]
Hi hartsantler, I like to think there's been a misunderstanding here. I've followed this project for a while and found the contributors to be good people.

It's extremely common for a large PR to be requested to be broken up into smaller PRs.

You seem to be quick to anger and reading through the comments you are way out of line. 
We all get frustrated in group coding sometimes but there are better ways to deal with it.

Promoting violence and name calling is so completely the anathema to how distributed open source projects are run, I would insta-ban you if I could.

Personally at the moment, I would rather abandon this PR than proceed. We don't need it unless it is offered with good grace and without caveats.

**Comment by akien-mga** [comment]
While any contribution to this repo is theoretically under the GPL, regardless of what further mood swings from their author, I wouldn't want to give @hartsantler any copyright to code merged in this codebase, so I prefer we don't touch any of this code.

If some fixes or features were valid, they can be reimplemented by someone with a positive attitude towards the project and its contributors and users.

@hartsantler has been banned.

**Comment by Jason0214** [comment]
Thank you all for the support, it really means a lot to me and, I believe, to the community as well.

To the people who watched this thread, I do see giving my suggestions for pull requests as a responsibility and I will keep doing it. I do think going through some discussions and revisions could help to improve the work. But it's merely suggestions, feel free to bring up any cool ideas and probably drafts as @akien-mga mentioned, we would be happy to see them and happy to  improve them if necessary. I hope there is no misunderstanding at this part.
Besides, if you have been watching this repo, it still has a lot of potential to improve, and generally I am not doing game developing, so it is extreme important that we can hear everyone's voice  and telling us what is you wanted and we can plan to do it.

Thanks all!

**Comment by zohozer** [comment]
As the title suggest, it is possible to export Grease Pencil objects to Godot using this add-on?

**Comment by bojidar-bg** [comment]
@zohozer That would be #267. Please avoid spamming this issue, as it was archived as well as split into multiple issues.
