### ISSUE TITLE
Error exporting Skeleton model

### ISSUE THREAD

**Issue by Antokolos** [godotengine/godot-blender-exporter#285]
**OS:**
WIN

**Godot version:**
3.1.1

**Blender version:**
2.79

**Issue description:**
Open attached skeleton model in Blender and try to export it.
Observe the following error
![image](https://user-images.githubusercontent.com/7196697/67474403-378be680-f676-11e9-8701-978a9373a73a.png)

In order to get rid from this error, I've fixed these NPEs in exporter code, this can be done with the following patch:
[skel.zip](https://github.com/godotengine/godot-blender-exporter/files/3766855/skel.zip)
This time there were no errors, but the animation does not work as expected in Godot, because the following nodes were generated:
![image](https://user-images.githubusercontent.com/7196697/67474875-f942f700-f676-11e9-8abd-1f9719e3c500.png)
AnimationPlayer under MeshInstance does not contain any animations. 
AnimationPlayer under Skeleton node does contain the test animation, but obvisously it does not affect the mesh, so that the skeleton is animated and the mesh is not animated.
Probably the mesh should be reworked in Blender (skeleton mesh should have the skeleton's skeleton as the parent). but the strange thing is, the animation works fine in Blender. 

**Minimal reproduction project:**

[skeleton_test.zip](https://github.com/godotengine/godot-blender-exporter/files/3766823/skeleton_test.zip)

**Comment by akien-mga** [comment]
What version of the exporter plugin are you using? For Blender 2.79 you should make sure to use https://github.com/godotengine/godot-blender-exporter/tree/blender2.79

**Comment by Antokolos** [comment]
Hmm, I think it is blender2.79:
`C:\work\godot\tools\godot-blender-exporter>git status                                                                                                          On branch blender2.79                                                                                                                                          Your branch is up-to-date with 'origin/blender2.79'`
