### ISSUE TITLE
Some animation frames don't get exported

### ISSUE THREAD

**Issue by fakedeltatime** [godotengine/godot-blender-exporter#308]
**OS:**
Manjaro Linux

**Godot version:**
v3.2.beta4.official

**Blender version:**
v2.81a

**Issue description:**
Only a part of my animation gets exported, ignoring half of the frames of some of the animated objects.

In Blender:
![gifcast_200104175727](https://user-images.githubusercontent.com/27518232/71768159-63500600-2f1c-11ea-871d-8f20a1ec5efb.gif)

In Godot:
![gifcast_200104175750](https://user-images.githubusercontent.com/27518232/71768163-66e38d00-2f1c-11ea-8564-6b35e7bb5a0f.gif)

Godot animation timeline:
![image](https://user-images.githubusercontent.com/27518232/71768186-7d89e400-2f1c-11ea-8a32-5f84d965afa5.png)

**Minimal reproduction project:**
I'm currently unable to reproduce it outside of my project, I'll try again later.

**Comment by Calinou** [comment]
Which format and exporter are you using?

**Comment by fakedeltatime** [comment]
Small update; if I press "apply scale" on the action strip in the NLA editor in Blender, the animation changes to what the exported animation is like in Godot.

**Comment by fakedeltatime** [comment]
Yeah this seems to be some sort of quirk with Blender instead of this exporter, the action editor is super confusing.
