### ISSUE TITLE
Incorrect normals

### ISSUE THREAD

**Issue by TheMoye** [godotengine/godot-blender-exporter#319]
**OS:**
Windows 10 64 Bits

**Godot version:**
Godot 3.2.rc4.official

**Blender version:**
Blender 2.83 Alpha, exporter downloaded on 28/01/2020

**Issue description:**
Mesh normals are not good.
In this example, they are created in Blender by the Weighted Normal modifier. The modifier is applied before exporting.
Below a picture with the normal rendering in Blender, the normal rendering with an exported mesh in ESCN and finally the normal rendering when exporting to Gltf 2.0.

![Blender-ESCN-Gltf](https://user-images.githubusercontent.com/46683101/73272558-ddee0780-41e2-11ea-9820-1bb29ee6356a.jpg)

**Comment by mysticfall** [comment]
I was about to report a similar issue, but I'm not entirely sure if it's the same problem. Here's a screenshot that shows my symptom:
![image](https://user-images.githubusercontent.com/2367032/74088150-59e72a00-4ad6-11ea-9bcb-66dd7edf7661.png)
Those were exported from the same Blend file - the above one using GLTF exporter, and the other using ESCN exporter. With the latter, I'm getting jagged triangular surfaces as shown in the image.

Here's my Blend file that can reproduce the problem:
[collar.zip](https://github.com/godotengine/godot-blender-exporter/files/4174587/collar.zip)

**Comment by Calinou** [comment]
@mysticfall Did you check **Triangulate Faces** before exporting the glTF (or use a Triangulate modifier and apply it upon exporting)?

It's recommended to let the 3D DCC triangulate on export rather than letting the engine do it for you (as the results aren't predictable).

**Comment by mysticfall** [comment]
No I didn't. But I'm having a problem with the ESCN exporter, not glTF one. Should I follow the steps you suggested with the ESCN exporter and see if it resolves the issue?

**Comment by mysticfall** [comment]
@Calinou Ok, I just tested it again after adding a `Triangulate` modifier with `Keep Normals` options on, and it indeed resolved the problem for me. Thanks for the help!

I still think that this better be fixed by the exporter itself though.
