### ISSUE TITLE
Re-exported escn does not show changes in Godot for previously contained objects

### ISSUE THREAD

**Issue by superlou** [godotengine/godot-blender-exporter#331]
**OS:**
Linux Mint 19.3

**Godot version:**
3.2.1 stable official

**Blender version:**
2.83 alpha

**Issue description:**
1. Create a scene in Blender.
2. Export via godot-blender-exporter into Godot project as "scene.escn."
3. Open escn export in Godot, but choose to create a "New Inherited" scene when prompted.
4. Open created tscn file and verify that blender scene is succesfully imported.
5. Edit mesh of model in Blender
6. Repeat step 2.
7. Reopen tscn file in Godot.

After step 7, the meshes of objects that previously existed are not updated. New objects are present. If I try to open the escn file without making a new inherited scene, the old objects also seem present.

8. Export the updated scene from blender as "scene2.escn."
9. Open scene2.escn in Godot.

After step 9, the updated meshes are all present. It seems as if once Godot has seen an object, it doesn't want to update the mesh, but if a new file is provided, Godot treats it as an updated file.

10. Rename scene.escn to scene3.escn in Godot.
11. Open scene3.escn in Godot.

After step 11, the updated meshes are all present. From this, it almost seems like this might be a Godot caching bug rather than a godot-blender-exporter issue, but maybe there is some hint to Godot that is missing in the export.

**Minimal reproduction project:**
Blender and Godot project files follow:
[blender.zip](https://github.com/godotengine/godot-blender-exporter/files/4500146/blender.zip)
[godot.zip](https://github.com/godotengine/godot-blender-exporter/files/4500147/godot.zip)

**Comment by superlou** [comment]
This might actually be a symptom of https://github.com/godotengine/godot/issues/21019 or https://github.com/godotengine/godot/issues/22450.

**Comment by superlou** [comment]
So I found that if I close all references to the escn file (including the tscn file inheriting it), then *delete the associated escn.import file*, Godot notices and creates a new escn.import file and the data is updated.

**Comment by Calinou** [comment]
This isn't a bug with the exporter, but rather a bug in the Godot editor. Closing.
