### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'action'

### ISSUE THREAD

**Issue by Denza755** [godotengine/godot-blender-exporter#339]
**OS:**

WIN

**Godot version:**

3.2.1

**Blender version:**

2.8.2.a

**Issue description:**

I created a simply car model with armature in Blender. Than exported it into fbx.
Than Godot Game Tools / Armature /Initialize Character / my fbx file

and get an error

Traceback (most recent call last):
  File "C:\Users\robbn\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\godot_game_tools\operators\character_controller.py", line 66, in execute
    characterArmature.animation_data.action.name = "T-Pose"
AttributeError: 'NoneType' object has no attribute 'action'

location: <unknown location>:-1

bpy.ops.wm_ggt.init_character(filepath="J:\\!_Blender_models_dis\\my1_4.fbx", files=[{"name":"my1_4.fbx"}])
bpy.context.area.ui_type = 'INFO'

**Minimal reproduction project:**

**Comment by Denza755** [comment]
there is a link to my1_4.fbx
https://drive.google.com/file/d/1enH2bmIkYcoAIQFJ50ThUSDKn-ByXJSZ/view?usp=sharing

**Comment by Calinou** [comment]
This repository is for the Godot Blender-to-escn exporter, not Godot Game Tools. You should report this issue on the [Godot Game Tools](https://github.com/vini-guerrero/Godot_Game_Tools) repository instead.

Still, keep in mind the Initialize Character action has known issues: https://github.com/vini-guerrero/Godot_Game_Tools/issues/11
