### ISSUE TITLE
-colonly not respected for empties

### ISSUE THREAD

**Issue by cbondurant** [godotengine/godot-blender-exporter#342]
**OS:**
Debian Stable (Buster)

**Godot version:**
3.0

**Blender version:**
2.81a

**Issue description:**
When exporting a scene with an empty marked -colonly the expected behavior is that based on its render shape it will be turned into a collider of the correct form. However it is instead exported as a simple Spacial node. 

**Minimal reproduction project:**
[colonly_test.zip](https://github.com/godotengine/godot-blender-exporter/files/4678277/colonly_test.zip)

You can tell that this is an exporting issue, as in the exported .escn created, the node is listed as type spacial. This issue also does not occur when using `-colonly` as a hint for mesh objects.

**Comment by cbondurant** [comment]
Are there any plans to work on this issue, or is this considered works as intended? I would appreciate a response of any kind, so I at least know if this is intentional behavior.

**Comment by Calinou** [comment]
I think it's a bug, but how is a render shape defined for an Empty?

**Comment by cbondurant** [comment]
Under the empty settings in blender there is one "Display As" setting that dictates the render style of the empty, notable options are circle, cube, sphere, and cone. with only one modifiable setting, a size parameter, which is unrelated to the transform's scale. 
![image](https://user-images.githubusercontent.com/12928246/86178826-1037c400-baf7-11ea-86a6-74b8e5a5ad5d.png)

There are other display options however they are not closed polygons, and could not be used for making collision objects.

I think at minimum it would make sense to support both box and sphere, as there are directly equivalent collision shapes for them in Godot. The BoxShape and SphereShape respectively.  These have the added benefit of being very optimized collision shapes, requiring simpler math to check for collisions than the respective complex polygons that often make up a scene, that would otherwise need to be done in the Godot editor.

**Comment by Calinou** [comment]
This is actually a bug at Godot's level, see https://github.com/godotengine/godot/issues/40729.
