### ISSUE TITLE
Animations not looping with -loop nor _loop, in NlaTracks, Actions, or Strips

### ISSUE THREAD

**Issue by fakedeltatime** [godotengine/godot-blender-exporter#346]
**OS:**
Manjaro Linux

**Godot version:**
3.2.1 stable

**Blender version:**
2.82a and 2.80, exporter redownloaded today from github.

**Issue description:**
Animations exported in a .escn file don't loop regardless of the suffix.

**Minimal reproduction project:**
[no_loop.zip](https://github.com/godotengine/godot-blender-exporter/files/4697410/no_loop.zip)

**Comment by Calinou** [comment]
Isn't this an issue with the Godot scene importer?

**Comment by fakedeltatime** [comment]
I suppose it would be, although the broken animations that I get from other export formats are able to loop when given the suffix. I'll try a newer build of Godot.

**Comment by fakedeltatime** [comment]
I returned to the Project List, exported again, then opened the project, closed all open scenes, selected the .escn file, reimported, and now everything works perfectly. If this happens again I'll update if only reimporting the file when all scenes including it are closed fixes it.

**Comment by fakedeltatime** [comment]
Closing all scenes that have the file as a child in them and reimporting it does seems to fix all the different artifacts that can come when importing.

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/issues/30302.
