### ISSUE TITLE
Too difficult to locate instructions for exporting multiple animations.

### ISSUE THREAD

**Issue by DellingF** [godotengine/godot-blender-exporter#349]
There's no way to easily locate instructions for exporting multiple animations.  I spent two weeks with this addon with no luck, because the instructions for correctly exporting a model with multiple animations were hidden in another issue thread:
https://github.com/godotengine/godot-blender-exporter/issues/311

I think a lot of potential users may be having an impossible time exporting armatures with multiple animations because this information is semi-hidden.  While I was eventually able to locate the instructions and employ them successfully, I think they should be posted to the project's front page along with the current installation instructions to save time and frustration for potential users..

**Comment by rcorre** [comment]
The animation flow is documented here: https://docs.godotengine.org/en/3.2/getting_started/workflow/assets/escn_exporter/animation.html

Based on a few issues like this, I'd say people don't know that doc exists. We should link to it from the README.
