### ISSUE TITLE
Print a warning message when trying to export unsupported light types (such as area lights)

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-blender-exporter#353]
**OS:** Any

**Godot version:** 3.2.2

**Blender version:** 2.83.2

**Issue description:**

The exporter should print a warning message when exporting a scene that contains light types that don't have Godot counterparts, such as area lights. Likewise, hemi lights with shadows are probably not representable in Godot either.

(This issue was requested by someone on IRC.)

**Comment by rcorre** [comment]
This [is implemented](https://github.com/rcorre/godot-blender-exporter/blob/564aa4f56cfe72be2d3c76893fe0380bb7548b8e/io_scene_godot/converters/simple_nodes.py#L146) already.

![1599477054](https://user-images.githubusercontent.com/2496231/92381712-59009000-f0d9-11ea-9955-cb41e35b6e1a.png)

Though I suppose "Unknown light type 'Area'. Use point, spot, or sun." might be a little more clear.
