### ISSUE TITLE
In mesh exporting one vertex incorrectly exported to (0, 0, 0)

### ISSUE THREAD

**Issue by Jason0214** [godotengine/godot-blender-exporter#36]
reproduce file:

[monster.blend.zip](https://github.com/godotengine/godot-blender-exporter/files/2061969/monster.blend.zip)

**Comment by sdfgeoff** [comment]
This seems to be the cause of #43 and #37 so hopefully fixing this will solve those as well.

Simple replication file:
[weight_bug.blend.zip](https://github.com/godotengine/godot-blender-exporter/files/2071382/weight_bug.blend.zip)

**Comment by sdfgeoff** [comment]
Solved in #44
