### ISSUE TITLE
cannot enable plugin

### ISSUE THREAD

**Issue by jellybeanstaffy** [godotengine/godot-blender-exporter#387]
**OS:**
linux mint 19.3

**Godot version:**
3.2.2

**Blender version:**
2.79b

**Issue description:**
![error](https://user-images.githubusercontent.com/40145818/102217013-e40cd580-3ed3-11eb-99c2-4c244d4e785d.png)

i followed installation instructions and this keeps happening. any ideas what it means or how to fix it?

**Minimal reproduction project:**

**Comment by Calinou** [comment]
The current version of the plugin doesn't support Blender 2.7x. You need to upgrade to Blender 2.81 or later.

**Comment by jellybeanstaffy** [comment]
is there any way to download a version compatible with 2.7x?

**Comment by Calinou** [comment]
> is there any way to download a version compatible with 2.7x?

You could probably find an old commit that works with 2.7x, but it's probably much buggier than the exporter is now.

**Comment by jellybeanstaffy** [comment]
yea, i probably will stick with the tried and tested gltf :)
thanks for your help

**Comment by Jason0214** [comment]
Btw, there is a [2.79 branch](https://github.com/godotengine/godot-blender-exporter/tree/blender2.79), but it also haven't been tested in a while.
Agree that glTF might be a better option for 2.79
