### ISSUE TITLE
Allow filtering non-deforming, or control bones when exporting

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot-blender-exporter#39]
* Version : `master` / 88a8803cd

When exporting a model with a lot of control bones (i.e. an IK setup), it is desirable to exclude such bones from being included in the exported result.

Better Collada has such an option which is quite useful in such a scenario, so it'd be good if we can implement the same feature in Blender exporter too.

Also, please consider this issue if you are going to follow the functionality in Better Collada exporter, godotengine/collada-exporter#60, as it's limiting its usability to some degree.

**Comment by Jason0214** [comment]
I implemented the armature exporting, it is naive, does not take groups and constrains into account. 
to be honest, I don't have much knowledge in armature and no idea of how the IK setup works, so could provide more detail on how to differentiate with a control bone from a pose bone and also other important feature to be have in armature exporting. It will help me to further improve it.

**Comment by mysticfall** [comment]
There is a check box to toggle if it should deform the associated mesh in Blender, when you select a specific bone in the pose mode.

And I think you can look at this line to see how Better Collada is handling it currently:

* https://github.com/godotengine/collada-exporter/blob/master/io_scene_dae/export_dae.py#L1091

**Comment by mysticfall** [comment]
You can also use my Blender file to test it, as it contains both deforming and non-deforming bones which are separated in different bone layers:

* https://github.com/mysticfall/AlleyCat/blob/master/Design/Blender/Characters/Human/Female/Body.blend

**Comment by Jason0214** [comment]
thank you very much! @mysticfall

**Comment by sdfgeoff** [comment]
@mysticfall It should now be working, so you should give it a test.

**Comment by mysticfall** [comment]
I found some minor differences with how Better Collada works. When a control bone is excluded which lies inbetween two non-control bones, it seems that Better Collada connects the remaining bones after removing the control bone while Blender exporter leave them orphaned, which can cause a problem with animations.

It's not a blocker issue, since I can manually change the bone hierarchy before exporting, but it's rather cumbersome so ideally, it'd be better handled by the exporter like Better Collada does.

Should I open a separate issue about it?

**Comment by Jason0214** [comment]
Open an issue about it.  Connect two bones separated by control bone is a desired feature.

Thank you very much for testing.
