### ISSUE TITLE
Are there any plans for this add-on?

### ISSUE THREAD

**Issue by antoni4040** [godotengine/godot-blender-exporter#4]
Hi! I'm interested in working on this addon, as I have done Blender addons in the past. So I was wondering if there are any official plans for this, how it should work etc. 
But first I would like to refactor and document it, if that's OK, as right now it's quite cryptic and it's difficult to understand what's going on. Also, what are the plans about the .escn filetype? Is there any documentation about its structure?

**Comment by kone9** [comment]
Please have someone make a flow chart for the poor newbies. XD

**Comment by antoni4040** [comment]
This has nothing to do with one's level of expertise. A well written specification of the filetypes used by Godot can help a lot in its adoption. Blender seems like a logical first step, but I'm sure that integration with other software is going to happen in the future.

**Comment by sdfgeoff** [comment]
My intended plans for the addon can be seen here:
https://github.com/simedis/godot-blender-exporter/wiki/Features
But this is in no way official.

You may also like to see Jason's GSOC proposal:
https://docs.google.com/document/d/1pvQ-By4cPw3SfWZtDFoyMaguTCfZn572lTQbw9yxaQs/edit

The escn file format is the same as the TSCN format, which I started documenting over here:
http://docs.godotengine.org/en/3.0/development/file_formats/tscn.html
