### ISSUE TITLE
I'm Sorry I can't find blender 2.79 addons, can someone please help

### ISSUE THREAD

**Issue by mecheware** [godotengine/godot-blender-exporter#404]
**OS:**

**Godot version:**

**Blender version:**

**Issue description:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
If you're using Blender 2.79, you can use the [Better Collada Exporter](https://github.com/godotengine/collada-exporter) add-on.

**Comment by Jason0214** [comment]
There is the 2.79 branch https://github.com/godotengine/godot-blender-exporter/tree/blender2.79, but as @Calinou said https://github.com/godotengine/collada-exporter is the better option.
