### ISSUE TITLE
Problem installing the Addon in Blender 2.79

### ISSUE THREAD

**Issue by gehvaugeh** [godotengine/godot-blender-exporter#5]
I freshly downloaded the new Blender 2.79 RC and then installed the godot exporter from user preferences menu. But it won't show up in the addons list, can somebody reproduce this behavior ?

**Comment by kone9** [comment]
The same thing happened to me, I checked the file, but I do not understand the code very much, so we'll have to wait for some mastermind to solve the problem

**Comment by gehvaugeh** [comment]
I have already loaded the python code itself into blender and did a test run in the text editor to see if any errors occure, but i seems all to be fine except that it does not show up in the addon list.

**Comment by LloydAlmeida** [comment]
@gehvaugeh I don't think you can install it directly from the Preferences.

Tested in 2.79.2 Linux 64bit
Download the Zip file,  from it extract the  io_scene_godot to your **/Blender/2.79/scripts/addons/** directory then go to the Preferences and Enable the Exporter (Its in the Import-Export section)
Hope this helps

**Comment by gehvaugeh** [comment]
Thx, i tried just copying the directory to the addon folder (as mentioned in the install instructions, sry for not reading carefully.. :-D) , now its working!

**Comment by sdfgeoff** [comment]
As far as I can tell, this means this issue has been resolved. If it hasn't, please create a new issue.
