### ISSUE TITLE
Connect deforming bones when they get orphaned by removing control bones

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot-blender-exporter#53]
When exporting with _Exclude Control Bones_ option, other deforming bones which were parented to one of the control bones removed by the option will get orphaned, potentially resulting in animation problems.

Better Collada, on the other hand, seems to handle such a situation by connecting such orphaned bones according to their hierarchical positions.

Again, you can test this feature with my model which I shared for another issue:
* https://github.com/mysticfall/AlleyCat/blob/master/Design/Blender/Characters/Human/Female/Body.blend

The bone hierarchy for the neck head area is as follows:
* `head` -> `struct_hd` -> `neck` -> `struct_nk` -> `spine03`

And the two bones whose name starts with `struct-` are controlling bones, thus get removed when being exported with the above mentioned option, leaving the former two orphaned. So, ideally it can be automatically connected again as:
* `head` -> `neck` -> `spine03`

After exporting the model, you can find those bones at the very end of the bones array.

**Comment by sdfgeoff** [comment]
Should be fixed in #54. If you could give it a test that would be great.
