### ISSUE TITLE
Apply PEP 8 style guide to the exporter code

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-blender-exporter#6]
The [PEP 8](https://pep8.org/) style should be applied to the Blender exporter code.

### Tools

- [autopep8](https://github.com/hhatto/autopep8)
- [PEP8 Speaks](https://pep8speaks.com/) (automatically scans pull requests for code style violations)

**Comment by sdfgeoff** [comment]
This has now been added, and all code after 0fc9d643d53b26455e197cc2cbb3baf5a77b7440 should be PEP8 compliant.
