### ISSUE TITLE
Add support for Inverse Kinematic

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot-blender-exporter#62]
It seems that IK is not implemented yet then we can't use rigify addon.

[Test IK.zip](https://github.com/godotengine/godot-blender-exporter/files/2237462/Test.IK.zip)

**Comment by guilhermefelipecgs** [comment]
When I say IK I mean just bake IK on keyframes like better collada exporter does.

**Comment by Jason0214** [comment]
@guilhermefelipecgs yes it is about baking constrain into action, I am currently working on it.  By the way, thank you for providing the test case, it is simple and helps a lot for development.

**Comment by guilhermefelipecgs** [comment]
Fixed by #63. Thanks!
