### ISSUE TITLE
Readme and license version

### ISSUE THREAD

**Issue by lupoDharkael** [godotengine/godot-blender-exporter#7]
[LICENSE.txt](https://github.com/godotengine/blender-exporter/blob/a12c20eb4bf09ccc8a0cec974a756f986bacbfd6/LICENSE.txt) contains the GPL 3 but the README says "GNU General Public License, version 2 or later"

**Comment by sdfgeoff** [comment]
@reduz As you are the original author I feel this is something you should make the decision on:
 - Should `LICENSE.txt` be down-dated to GPLv2 as in #8 
 - Should `README.md` and the code header be changed to reference GPL v3

Also, should all the code files contain the license header? Currently only export_godot.py contains it.

**Comment by reduz** [comment]
Probably version 2. but whathever you guys think it's better. I don't know, I just used the same license as Blender back then.

**Comment by reduz** [comment]
And as I based this one on the Better Collada exporter, just tried to use the same license

**Comment by sdfgeoff** [comment]
Ok, I'll accept the PR, and we'll stick with GPL v2. I just read [the differences](https://www.gnu.org/licenses/rms-why-gplv3.en.html), and the change doesn't seem to apply to us (unless someone makes a hardware-embedded godot file-format exporter!?).
