### ISSUE TITLE
escn output does not look like blender rendering

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot-blender-exporter#70]
I've got a simple blender model that looks like this:

![blender](https://user-images.githubusercontent.com/2496231/43838583-cc44d7da-9ae9-11e8-9abb-37df4a68ecbe.png)

Exporting with the [better collada exporter](https://github.com/godotengine/collada-exporter) results in a similar-looking model in godot:

![godot_dae](https://user-images.githubusercontent.com/2496231/43838582-cc36d720-9ae9-11e8-8a05-adb91eb16d38.png)

When I export to .escn, however, it looks like the sides of the ship are "caved-in":

![godot_escn](https://user-images.githubusercontent.com/2496231/43838581-cc290118-9ae9-11e8-93ea-1c6864da803b.png)

I'm new to godot and blender, so it could be that I designed my model poorly, but since the collada exporter seems to get it "right", it could be a bug in the .escn exporter.

[blender_file.zip](https://github.com/godotengine/godot-blender-exporter/files/2270333/blender_file.zip)

**Comment by sdfgeoff** [comment]
When I looked at the images, my immediate thought was "it looks like a triangulation problem. Did he use quads for the sides?" But upon opening the blend file, I see it has what looks like a mesh made only from triangles. BUT for some reason, the mesh changes when I triangulate it again (ctrl+t). And if I save the triangulated mesh as escn, then it exports correctly.

In edit mode, face select, I see this:
![singleface](https://user-images.githubusercontent.com/13490050/43840392-e3383342-9b20-11e8-97a0-405ab54c3708.png)
Which shows that the whole side of the mesh is a single quad that is significantly non-planar, and I can delete the two edges that "define" the sides and the side faces still exist. 

So in the end it is a case of a "bad" model where you have a quad that isn't flat. The difference between the collada exporter and the escn exporter is just which way they triangulate that quad.

The solution: press ctrl+t to triangulate the mesh.

**Comment by rcorre** [comment]
Thanks for the rapid response, and for taking the time to investigate and explain! Seems like I have a lot to learn :)
