### ISSUE TITLE
Timeline export with multiple skeletons and modifiers does not seem to work

### ISSUE THREAD

**Issue by reduz** [godotengine/godot-blender-exporter#75]
Attaching project, seems to work fine with Better Collada (Option: Export animations but not multiple actions)
[IK-GRABTEXT.zip](https://github.com/godotengine/godot-blender-exporter/files/2275262/IK-GRABTEXT.zip)

How it should look:
![main_timeline](https://user-images.githubusercontent.com/6265307/43915811-3e811e8c-9be2-11e8-8d98-4946647c4f86.gif)

**Comment by Jason0214** [comment]
I guess I can add  a similar option to export all the action in the scene to a single AnimationPlayer

**Comment by reduz** [comment]
@Jason0214 I think there should probably be 3 export modes:

1. Actions: Just export an animationplayer per object that uses animation, with their respective actions.
2. NLA: Export a global animation player that starts the relevant action. I guess similar to NLA? Not sure how possible is this
3. Global: Simply export the global animation timeline as one single animation, no actions or animationplayers per object.

**Comment by Jason0214** [comment]
the NLA mode would be export every object's action as different animation resource and all put into one AnimationPlayer.  is that right?

**Comment by reduz** [comment]
@Jason0214 yeah, every object would have their own animationplayer. The scene would also have one and then control when those are activated across the timeline. This is supported by AnimationPlayer already.

**Comment by Jason0214** [comment]
I think this issue is fixed now, this thread would be closed.
