### ISSUE TITLE
Can't export complex rigged/animated scene

### ISSUE THREAD

**Issue by reduz** [godotengine/godot-blender-exporter#78]
This is the player from the [TPS demo](https://www.youtube.com/watch?v=btazdd8jNEc). Fails on export.
It contains multiple actions which should be exported as separate animations in the escn file. Works fine with BetterCollada.

[player.zip](https://github.com/godotengine/godot-blender-exporter/files/2302282/player.zip)

**Comment by Jason0214** [comment]
Now an incorrect fcurve path would not crash the exporter, this thread would be closed.
