### ISSUE TITLE
Cycles materials are not coming through in Godot.

### ISSUE THREAD

**Issue by psiker** [godotengine/godot-blender-exporter#89]
After seeing a post on the godot facebook group that blender scenes with cycles materials could be exported to godot with this plugin I immediately gave it a try with a scene from a tutorial series I'm doing. The materials are pretty complex. Of course for in game they need to be baked, but this was just for testing purposes. The Objects, geometry and lights are coming through, but not the cycles materials. This would be really nice if they did.
![testblender2godotplugin01-nomaterials](https://user-images.githubusercontent.com/15362571/44971512-248bf380-af56-11e8-82af-f208ff3aecd0.png)

I've made a simpeler scene with very basic cycles materials on a few suzannes. One with just a diffuse color, red, one with just a checker image texture, groenSchaakbord.png, and one with principled shader using the same texture and Metallic value 1. I don't see any materials in Godot again. 
![testblender2godotplugin03-nomaterials](https://user-images.githubusercontent.com/15362571/44971841-58b3e400-af57-11e8-9b88-cf0a10d614f5.png)

Here is the second test scene:
[github issue blender godot export import.zip](https://github.com/godotengine/godot-blender-exporter/files/2344497/github.issue.blender.godot.export.import.zip)

**Comment by sdfgeoff** [comment]
This is still an unmerged PR #56 - which will hopefully be merged soon (just need to discuss some licensing things to do with our test scenes). You could try that PR.

But be aware that many many nodes are not currently supported yet.

**Comment by Jason0214** [comment]
cycle material branch is already merged, close this thread for now. If there are issues found in material exporting, feel free to reopen.
