### ISSUE TITLE
Unable to keep meshes as separate files

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot-blender-exporter#93]
I'm not too sure if it's an issue with the exporter or Godot itself. But when I change import settings for `*.escn` to store meshes as separate files, a file with a blank name (_'.mesh'_) is generated after the importing process, making Godot crash when trying to open the modified `.escn` file.

**Comment by reduz** [comment]
This most likely have to be with the exporter not setting names to meshes

**Comment by Jason0214** [comment]
Seems fixed, thread would be closed.
